# Generated by Django 2.2.17 on 2021-10-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='PublicExperience',
            name='approved',
            field=models.CharField(default='not reviewed', max_length=50),
        ),
        migrations.AddField(
            model_name='PublicExperience',
            name='difference_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='PublicExperience',
            name='experience_id',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
