# Generated by Django 2.2.17 on 2022-11-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_add_fields_to_public_experiences'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicexperience',
            name='title_text',
            field=models.TextField(default=''),
        ),
    ]
