# Generated by Django 2.2.3 on 2019-09-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_publicexperience_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicexperience',
            name='difference_text',
            field=models.TextField(default=''),
        ),
    ]
