# Generated by Django 2.2.17 on 2023-01-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20230105_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicexperience',
            name='research',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='publicexperience',
            name='other',
            field=models.TextField(default=''),
        ),
    ]
