# Generated by Django 2.2.17 on 2023-02-06 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20230123_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.TextField()),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('changed_by', models.TextField()),
                ('change_comments', models.TextField(default='')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PublicExperience')),
            ],
        ),
    ]
