# Generated by Django 2.2.17 on 2023-03-27 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_experiencehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencehistory',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openhumans.OpenHumansMember'),
        ),
    ]
