# Generated by Django 4.2 on 2023-05-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20230327_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencehistory',
            name='change_reply',
            field=models.TextField(default=''),
        ),
    ]
