# Generated by Django 4.2 on 2023-07-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_experiencehistory_change_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicexperience',
            name='experience_authorship',
            field=models.CharField(default='AutSPACEs contributor', max_length=100),
        ),
    ]
