# Generated by Django 4.2.3 on 2023-08-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_experiencehistory_change_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicexperience',
            name='authorship_relation',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='publicexperience',
            name='first_hand_authorship',
            field=models.BooleanField(choices=[(False, "Experience is someone else's"), (True, 'Experience is my own')], default=False),
        ),
    ]
