# Generated by Django 4.2 on 2023-06-30 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('age_bracket', models.TextField(default='unspecified')),
                ('description', models.TextField(default='')),
                ('gender', models.TextField(default='unspecified')),
                ('autistic_identification', models.TextField(default='unspecified')),
                ('location', models.TextField(default='')),
                ('abuse', models.BooleanField(default=False)),
                ('drug', models.BooleanField(default=False)),
                ('mentalhealth', models.BooleanField(default=False)),
                ('negbody', models.BooleanField(default=False)),
                ('violence', models.BooleanField(default=False)),
                ('other', models.BooleanField(default=False)),
                ('comms_review', models.BooleanField(default=False)),
                ('profile_submitted', models.BooleanField(default=False)),
            ],
        ),
    ]
