# Generated by Django 4.2.3 on 2023-08-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_refine_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='autistic_identification',
            field=models.TextField(default=''),
        ),
    ]
